<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_webgallery
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

if( AKDEBUG ){
    WebgalleryHelper::_('include.quickedit');
}


// Init some API objects
// ================================================================================
$app     = JFactory::getApplication() ;
$date    = JFactory::getDate( 'now' , JFactory::getConfig()->get('offset') ) ;
$doc     = JFactory::getDocument();
$uri     = JFactory::getURI() ;
$user    = JFactory::getUser();
$userId  = $user->get('id');



// List Control
// ================================================================================
$nested     = $this->state->get('items.nested') ;
$listOrder  = $this->state->get('list.ordering');
$listDirn   = $this->state->get('list.direction');
$orderCol   = $this->state->get('list.orderCol', 'a.ordering') ;
$canOrder   = $user->authorise('core.edit.state', 'com_webgallery');
$saveOrder  = $listOrder == $orderCol || ($listOrder == 'a.lft' && $listDirn == 'asc');
$trashed    = $this->state->get('filter.published') == -2 ? true : false;
$show_root  = JRequest::getVar('show_root') ;


// For Joomla!3.0
// ================================================================================
if( JVERSION >= 3 ) {
    if ($saveOrder)
    {
        $method = $nested ? 'saveOrderNestedAjax' : 'saveOrderAjax' ;
        $saveOrderingUrl = 'index.php?option=com_webgallery&task=queues.'.$method.'&tmpl=component';
        JHtml::_('sortablelist.sortable', 'itemList', 'adminForm', strtolower($listDirn), $saveOrderingUrl, false, $nested);
    }
}
?>

<!-- List Table -->
<table class="table table-striped adminlist" id="itemList">
    <thead>
        <tr>

            <!--CHECKBOX-->
            <th width="1%" class="center">
                <input type="checkbox" name="checkall-toggle" value="" onclick="Joomla.checkAll(this)" />
            </th>
            
            <!--ITEM TITLE-->
            <th class="center">
                <?php echo JHtml::_('grid.sort',  'COM_WEBGALLERY_ITEM_TITLE', 'b.title', $listDirn, $listOrder); ?>
            </th>
            
            <!--STATUS-->
            <th width="5%" class="nowrap center">
                <?php echo JHtml::_('grid.sort',  'COM_WEBGALLERY_QUEUE_DESC', 'a.status', $listDirn, $listOrder); ?>
            </th>
            
            <!--CREATED-->
            <th width="10%" class="center">
                <?php echo JHtml::_('grid.sort',  'JDATE', 'a.created', $listDirn, $listOrder); ?>
            </th>
            
            <!--ID-->
            <th width="1%" class="nowrap center">
                <?php echo JHtml::_('grid.sort',  'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?>
            </th>

        </tr>
    </thead>
    
    <!--PAGINATION-->
    <tfoot>
        <tr>
            <td colspan="15">
                <div class="pull-left">
                    <?php echo $this->pagination->getListFooter(); ?>
                </div>
                
                <?php if( JVERSION >= 3 ): ?>
                <!-- Limit Box -->
                <div class="btn-group pull-right hidden-phone">
                    <label for="limit" class="element-invisible"><?php echo JText::_('JFIELD_PLG_SEARCH_SEARCHLIMIT_DESC');?></label>
                    <?php echo $this->pagination->getLimitBox(); ?>
                </div>
                <?php endif; ?>
            </td>
        </tr>
    </tfoot>
    
    
    <tbody>
    <?php foreach ($this->items as $i => $item) :
        
        $item = new JObject($item);
        
        $ordering   = ($listOrder == $orderCol);
        $canEdit    = $user->authorise('core.edit',         'com_webgallery.queue.'.$item->a_id);
        $canCheckin = $user->authorise('core.edit.state',   'com_webgallery.queue.'.$item->a_id) || $item->get('a_checked_out') == $userId || $item->get('a_checked_out') == 0;
        $canChange  = $user->authorise('core.edit.state',   'com_webgallery.queue.'.$item->a_id) && $canCheckin;
        $canEditOwn = $user->authorise('core.edit.own',     'com_webgallery.queue.'.$item->a_id) && $item->get('a_created_by') == $userId;
        
        
        
        // Nested ordering
        // ================================================================
        if($nested){
            
            if($item->a_id == 1) {
                $item->a_title = JText::_('JGLOBAL_ROOT') ;
                $canEdit    = false ;
                $canChange  = false ;
                $canEditOwn = false ;
            }
            
            $orderkey = array_search($item->a_id, $this->ordering[$item->a_parent_id]);
        
            // Get the parents of item for sorting
            if ($item->a_level > 1)
            {
                $parentsStr = "";
                $_currentParentId = $item->a_parent_id;
                $parentsStr = " ".$_currentParentId;
                for ($n = 0; $n < $item->a_level; $n++)
                {
                    foreach ($this->ordering as $k => $v)
                    {
                        $v = implode("-", $v);
                        $v = "-".$v."-";
                        if (strpos($v, "-" . $_currentParentId . "-") !== false)
                        {
                            $parentsStr .= " ".$k;
                            $_currentParentId = $k;
                            break;
                        }
                    }
                }
            }
            else
            {
                $parentsStr = "";
            }
        }
        // ================================================================
        // Nested ordering END

        ?>
        <tr class="row<?php echo $i % 2; ?>">      
            <!--CHECKBOX-->
            <td class="center">
                <?php echo JHtml::_('grid.id', $i, $item->a_id); ?>
            </td>
     		
     		<!--ITEM TITLE-->
            <td class="center">
                <?php echo $item->get('b_title'); ?>
            </td>
            
            <!--STATUS-->
            <td class="center">
                <?php           
                	$status = $item->get('a_status') ;      	
                	if( $status == 0){
						echo JText::_('COM_WEBGALLERY_QUEUE_STATUS_UNDO') ;
					}
					else if( $status == 1){
						echo JText::_('COM_WEBGALLERY_QUEUE_STATUS_IN_PROCCESS') ;
					}					
					else {
						echo JText::_('COM_WEBGALLERY_QUEUE_STATUS_DONE') ;
					}
                ?>
            </td>
            
            
            <!--CREATED-->
            <td class="center">
                <?php echo JHtml::_('date', $item->get('a_created'), JText::_('DATE_FORMAT_LC4')); ?>
            </td>
            
            
            <!--ID-->
            <td class="center">
                <span
                    <?php if( $nested ): ?>
                    class="hasTip" title="<?php echo $item->a_lft.'-'.$item->a_rgt; ?>"
                    <?php endif; ?>
                ><?php echo (int) $item->get('a_id'); ?></span>
            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>