<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_webgallery
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once JPATH_ADMINISTRATOR.'/components/com_webgallery/includes/core.php' ;
JForm::addFieldPath( AKPATH_FORM.'/fields');
JFormHelper::loadFieldClass('itemlist');

/**
 * Supports an HTML select list of categories
 */
class JFormFieldQueue_List extends JFormFieldItemlist
{
    /**
     * The form field type.
     *
     * @var string
     */
    public $type = 'Queue_List';
    
    /**
     * List name.
     *
     * @var string 
     */
    protected $view_list = 'queues' ;
    
    /**
     * Item name.
     *
     * @var string 
     */
    protected $view_item = 'queue' ;
    
    /**
     * Extension name, eg: com_content.
     *
     * @var string 
     */
    protected $extension = 'com_webgallery' ;
    
    /**
     * Set the published column name in table.
     *
     * @var string
     */
    protected $published_field = 'published' ;
    
    /**
     * Set the ordering column name in table.
     *
     * @var string
     */
    protected $ordering_field = null ;
}