<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_webgallery
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once JPATH_ADMINISTRATOR.'/components/com_webgallery/includes/core.php' ;
JForm::addFieldPath( AKPATH_FORM.'/fields');
JFormHelper::loadFieldClass('Modal');

/**
 * Supports a modal picker.
 */
class JFormFieldQueue_Modal extends JFormFieldModal
{
    /**
     * The form field type.
     *
     * @var string
     * @since    1.6
     */
    protected $type = 'Queue_Modal';
    
    /**
     * List name.
     *
     * @var string 
     */
    protected $view_list = 'queues' ;
    
    /**
     * Item name.
     *
     * @var string 
     */
    protected $view_item = 'queue' ;
    
    /**
     * Extension name, eg: com_content.
     *
     * @var string 
     */
    protected $extension = 'com_webgallery' ;
    
}
