<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_webgallery
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JHtml::_('behavior.framework', true);
WebgalleryHelper::_('include.bootstrap', true, true);

$doc = JFactory::getDocument();
$doc->addScript('components/com_webgallery/includes/js/slideshow/js/slideshow.js');
$doc->addStylesheet('components/com_webgallery/includes/js/slideshow/css/slideshow.css');

// Create shortcuts to some parameters.
$params     = $this->item->params;
$canEdit    = $this->item->params->get('access-edit');
$user       = JFactory::getUser();
$item       = $this->item ;
$uri        = JFactory::getURI() ;
$model		= $this->getModel();
?>
<style type="text/css">
    
    /* Overriding the default Slideshow thumbnails for the vertical presentation */


    .slideshow-thumbnails ul {
    	height: 70px;
    	width: 70px;
    }
</style>
<script type="text/javascript">
    jQuery('.dropdown-toggle').dropdown();
    
    window.addEvent('domready', function(){
	    var data = <?php echo json_encode($this->imgs); ?>;
	    var myShow = new Slideshow('content-img', data, { controller: true, height: 320, hu: '<?php echo JURI::root(true); ?>/images/webgallery/<?php echo $this->item->id; ?>', thumbnails: true, width:560 });
	});
</script>
<form action="<?php echo JRoute::_('index.php?option=com_webgallery&view=item'); ?>" method="post" name="adminForm" id="adminForm" enctype="multipart/form-data">

    <div id="Webgallery" class="windwalker item container-fluid item<?php echo $this->get('pageclass_sfx');?>">
        <div id="webgallery-wrap-inner">
            
            <div class="item-item item<?php if($item->published == 0) echo ' well well-small'; ?>">
                <div class="item-item-inner">
                    
                    
                    <?php if ($canEdit) : ?>
                    <!-- Edit -->
                    <!-- ============================================================================= -->
                    <div class="edit-icon btn-toolbar fltrt">
                        <div class="btn-group">
                            <?php echo JHtml::_( 'link', JRoute::_('index.php?option=com_webgallery&task=item.edit&id='.$item->id.'&return='.WebgalleryHelper::_('uri.base64', 'encode', $uri->toString())) , JText::_('JTOOLBAR_EDIT'), array( 'class' => 'btn btn-small' ) ); ?>
                            <button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb<?php echo $item->id; ?>','items.publish')" title="啟用"><?php echo JText::_('JTOOLBAR_ENABLE'); ?></a>
                                </li>
                                <li>
                                    <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb<?php echo $item->id; ?>','items.unpublish')" title="停用"><?php echo JText::_('JTOOLBAR_DISABLE'); ?></a>
                                </li>
                            </ul>
                          </div>
                        
                    </div>
                    <div style="display: none;">
                        <?php echo JHtml::_('grid.id', $item->id, $item->id); ?>
                    </div>
                    <!-- ============================================================================= -->
                    <!-- Edit End -->
                    <?php endif; ?>
                    
                    
                    
                    <!-- Heading -->
                    <!-- ============================================================================= -->
                    <div class="heading">
                        <h2><?php echo $params->get('link_titles', 1) ? JHtml::_('link', $item->link, $item->title) : $item->title ?></h2>
                    </div>
                    <!-- ============================================================================= -->
                    <!-- Heading -->
                    
                    
                    
                    <!-- afterDisplayTitle -->
                    <!-- ============================================================================= -->
                    <?php echo $this->item->event->afterDisplayTitle; ?>
                    <!-- ============================================================================= -->
                    <!-- afterDisplayTitle -->
                    
                    
                    <!-- beforeDisplayContent -->
                    <!-- ============================================================================= -->
                    <?php echo $this->item->event->beforeDisplayContent; ?>
                    <!-- ============================================================================= -->
                    <!-- beforeDisplayContent -->
                    
                    
                    <!-- Info -->
                    <!-- ============================================================================= -->
                    <div class="info">
                        <div class="info-inner">
                            <?php echo $this->showInfo($item, 'cat_title',   'jcategory', null, JRoute::_('index.php?option=com_webgallery&view=items&id='.$item->get('catid'))); ?>
                            <!--
                            <?php echo $this->showInfo($item, 'created',     'com_webgallery_created', null); ?>
                            <?php echo $this->showInfo($item, 'modified',    'com_webgallery_modified', null); ?>
                            <?php echo $this->showInfo($item, 'created_user','com_webgallery_created_by', null); ?>
                            -->
                        </div>
                    </div>
                    
                    <hr class="info-separator" />
                    <!-- ============================================================================= -->
                    <!-- Info -->
                    
                    
                    <?php if ($params->get('show_tags', 1) && !empty($this->item->tags)) : ?>
						<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
				
						<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
					<?php endif; ?>
                    
                    <br />
                    <!-- Content -->
                    <!-- ============================================================================= -->
                    <div class="content">
                        <div class="content-inner row-fluid">
                            
                            <div class="span12">
                                <div id="content-img" class="content-img" style="position: relative; margin-bottom: 70px;>
                                    <?php echo JHtml::_('image', $item->id, $item->title); ?>
                                </div>
                                
                                <div class="text">
                                    <?php echo $item->text; ?>
                            	</div>  
                            </div>
                            
                           
                            
                        </div>
                    </div>
                    <!-- ============================================================================= -->
                    <!-- Content End -->
                    
                    
                    <!-- afterDisplayContent -->
                    <!-- ============================================================================= -->
                    <?php echo $this->item->event->afterDisplayContent; ?>
                    <!-- ============================================================================= -->
                    <!-- afterDisplayContent -->
                    
                    
                    
                </div>
            </div>
            
        </div>
    </div>
    
    <div>
        <input type="hidden" name="task" value="" />
        <input type="hidden" name="boxchecked" value="0" />
        <input type="hidden" name="return" value="<?php echo base64_encode($uri->toString()); ?>" />
        <?php echo JHtml::_('form.token'); ?>
    </div>
</form>        
