<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_webgallery
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$doc     = JFactory::getDocument();
$app     = JFactory::getApplication();
$lang    = JFactory::getLanguage();



// Include Helpers
// ========================================================================

// Core init, it can use by module, plugin or other component.
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_webgallery/includes/core.php" ) ;

// Set default option to path helper, then AKHelperPath will helpe us get admin path.
AKHelper::_('path.setOption', 'com_webgallery') ;


// Some useful settings
if( $app->isSite() ){
    
    // Include Admin language as global language.
    $lang->load('', JPATH_ADMINISTRATOR);
    $lang->load('com_webgallery', JPATH_COMPONENT_ADMINISTRATOR );
    WebgalleryHelper::_('lang.loadAll', $lang->getTag());

    // Include Joomla! admin css
    WebgalleryHelper::_('include.sortedStyle', 'includes/css');
    
    // set Base to fix toolbar anchor bug
    $doc->setBase( JFactory::getURI()->toString() );
    
}else{
    WebgalleryHelper::_('lang.loadAll', $lang->getTag());
    WebgalleryHelper::_('include.sortedStyle', 'includes/css');
}

// Include Fields
JForm::addFieldPath( AKPATH_FORM.'/fields');

// Detect version
WebgalleryHelper::_('plugin.attachPlugins');

// Debug
define('AKDEBUG', WebgalleryHelper::_('system.getConfig', 'system.debug', false, 'com_webgallery')) ;
define('AKDEV', WebgalleryHelper::_('system.getConfig', 'system.development_mode', true, 'com_webgallery')) ;


/* API Client init 
AKHelper::_('api.initClient', null , array(
    'username'     => 'username' ,
    'password'     => 'password' ,
    'host'         => '' ,
    'component' => 'com_webgallery'
) );
*/

include_once WEBGALLERY_ADMIN . '/class/thumb.php';